#!/bin/sh /etc/rc.common

START=90
STOP=01
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /bin/sh "/usr/sbin/mesh11sd"
	procd_append_param command daemon
	procd_close_instance
}

stop_service() {
	/sbin/uci revert wireless
}

