#!/bin/sh /etc/rc.common

START=90
STOP=01
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /bin/sh "/usr/sbin/mesh11sd"
	procd_append_param command daemon
	procd_set_param pidfile /var/run/mesh11sd.pid
	procd_set_param term_timeout 1
	procd_set_param stdout 1
	procd_set_param respawn 150 10 10
	procd_close_instance
}

stop_service() {
	/sbin/uci revert mesh11sd
	/sbin/uci revert wireless
	/sbin/uci revert dhcp

}

